# Adapted from: https://medium.com/geekculture/deploying-influxdb-2-0-using-docker-6334ced65b6c

services:
  influxdb:
    image: influxdb:2.2-alpine
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - /srv/influxdb/influxdb2:/var/lib/influxdb2
      - /srv/influxdb/config.yml:/etc/influxdb2/config.yml
