#!/bin/sh

# Copyright (C) 2022  Nick Schlobohm <nks@schlobohm.one>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

while test $# -gt 0; do
  case "$1" in
    inject)
        while read l; do
            k="$(echo $l | cut -d '=' -f 1)" # key
            v="$(echo $l | cut -d '=' -f 2)" # value
            grep --exclude-dir=".git" --exclude="README.md" -rl "{{$k}}" . | xargs sed -i "s/{{$k}}/$v/g"
        done <VARIABLES
      shift
      ;;
    *)
      break
      ;;
  esac
  exit 0
done

grep --exclude-dir=".git" --exclude="README.md" --exclude="$0" -roh "{{[^{} \$]*}}" . | sed 's/[{}]//g' | uniq | awk '{ print $0 "=change_me" }' > VARIABLES
echo "VARIABLES file generated. Edit that file as necessary, and then run the 'prepare-variables' script again with the 'inject' option."
