# Adapted from: https://grafana.com/docs/grafana/latest/installation/docker/
# and: https://grafana.com/docs/grafana/latest/administration/configure-docker/

services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /srv/grafana:/var/lib/grafana
