version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
      - 8123:8123 # for Dynmap, disable if not using that plugin
    environment:
      EULA: "TRUE"
      TYPE: "SPIGOT"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - /srv/minecraft:/data
