- name: Clone IaC repo to /srv
  hosts: "*"
  tasks:
    - name: Clone IaC repo to /srv
      ansible.builtin.git:
        repo: https://github.com/schlobohm/iac.git
        dest: /srv/iac
        force: yes
